### ISSUE TITLE
wp10 API returns an array instead of a hash for some revisions

### ISSUE THREAD

**Issue by ragesoss** [wikimedia/ores#139]
What is going on here?
https://ores.wmflabs.org/v1/scores/enwiki/wp10/?revids=712439107

This has been the way it returns most results: https://ores.wmflabs.org/v1/scores/enwiki/wp10/?revids=11111

I think this is new. I never hit any errors from it until yesterday.

**Comment by aptvaibhav** [comment]
can u please share more details regarding this bug.

**Comment by halfak** [comment]
Looks like this is resolved.
